### ISSUE TITLE
Support for GraphicsMagick

### ISSUE THREAD

**Issue by cblock** [keichan34/exfile-imagemagick#7]
Hi!

Over at [http://www.github.com/cblock/exfile-graphicsmagick](http://www.github.com/cblock/exfile-graphicsmagick) I created a clone of this repo that runs GraphicsMagick instead of ImageMagick. Initially I thought this could be added to the exfile description as an alternative to exfile-imagemagick. But essentially the only thing I did was to replace  system calls to `convert` with `GM convert` etc. 

So now I think it's not worth the duplication of code and I propose to add a config switch to this repo that lets users choose which library to use. What do you think?

**Comment by keichan34** [comment]
I don't see a problem with that. Would you prefer an explicit configuration option, or should the library detect if GM is available and automatically use that, falling back on ImageMagick?

**Comment by cblock** [comment]
I'd prefer an explicit config option with imagemagick being the default config. That way one can explicitly control which library to use.

**Comment by keichan34** [comment]
Sounds good!
